import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        LoadBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        CurrentDatabase = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        Insert_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("GUI_Frame"); // NOI18N

        SearchBox.setFont(new java.awt.Font("TH Sarabun New", 1, 22)); // NOI18N

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FirstName", "LastName", "Faculty", "GPAX"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        LoadBtn.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        LoadBtn.setText("LOAD");
        LoadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoadBtnMouseClicked(evt);
            }
        });

        ClearBtn.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        ClearBtn.setText("CLEAR");
        ClearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearBtnMouseClicked(evt);
            }
        });

        CurrentDatabase.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        CurrentDatabase.setText("Current Database : ");

        StatusLabel.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N
        StatusLabel.setText("None");

        Insert_Btn.setBackground(new java.awt.Color(0, 102, 255));
        Insert_Btn.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        Insert_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Insert_Btn.setText("INSERT");
        Insert_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Insert_BtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CurrentDatabase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatusLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LoadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Insert_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(110, 110, 110)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(LoadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Insert_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentDatabase)
                    .addComponent(StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoadBtnMouseClicked
        // TODO add your handling code here:
        Connection conn = null;
        try {
            String dbUrl = "jdbc:mysql://localhost/dbtable";
            conn = DriverManager.getConnection(dbUrl, "root", "");

            //Statement stmt = conn.createStatement();
            String Search = SearchBox.getText().trim();
            //String queryStudents = "select * from students";
            String query = "SELECT * FROM students WHERE ID LIKE ? OR FirstName LIKE ? OR LastName LIKE ? OR Faculty LIKE ? OR GPAX LIKE ?";

            PreparedStatement ptmt = conn.prepareStatement(query);
            ptmt.setString(1, "%" + Search + "%");
            ptmt.setString(2, "%" + Search + "%");
            ptmt.setString(3, "%" + Search + "%");
            ptmt.setString(4, "%" + Search + "%");
            ptmt.setString(5, "%" + Search + "%");

            ResultSet rs = ptmt.executeQuery();

            StatusLabel.setText(dbUrl);

            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                long id = rs.getLong("ID");
                String fname = rs.getString("FirstName");
                String lname = rs.getString("LastName");
                String faculty = rs.getString("Faculty");
                double gpax = rs.getDouble("GPAX");

                model.addRow(new Object[]{id, fname, lname, faculty, gpax});
            }

        } catch (SQLException ex) {
            StatusLabel.setText("Connection failed");
            System.out.println("SQLException: " + ex.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println("SQLException: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_LoadBtnMouseClicked

    private void ClearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBtnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
        StatusLabel.setText("None");
    }//GEN-LAST:event_ClearBtnMouseClicked

    private void Insert_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Insert_BtnMouseClicked
        // TODO add your handling code here:
        Insert_GUI insert = new Insert_GUI();
        insert.show();
        insert.setDefaultCloseOperation(Insert_GUI.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_Insert_BtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel CurrentDatabase;
    private javax.swing.JButton Insert_Btn;
    private javax.swing.JButton LoadBtn;
    private javax.swing.JTextField SearchBox;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
