
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Insert_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Insert_GUI
     */
    public Insert_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_txt = new javax.swing.JLabel();
        ID_Label = new javax.swing.JLabel();
        Fname_Label = new javax.swing.JLabel();
        Lname_Label = new javax.swing.JLabel();
        Fac_Label = new javax.swing.JLabel();
        GPAX_Label = new javax.swing.JLabel();
        ID_Box = new javax.swing.JTextField();
        Fname_Box = new javax.swing.JTextField();
        Lname_Box = new javax.swing.JTextField();
        Fac_Box = new javax.swing.JTextField();
        GPAX_Box = new javax.swing.JTextField();
        Submit_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INSERT DATA");

        Title_txt.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        Title_txt.setText("INSERT DATA");

        ID_Label.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        ID_Label.setText("ID :");

        Fname_Label.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        Fname_Label.setText("Firstname :");

        Lname_Label.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        Lname_Label.setText("Lastname :");

        Fac_Label.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        Fac_Label.setText("Faculty :");

        GPAX_Label.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        GPAX_Label.setText("GPAX :");

        ID_Box.setFont(new java.awt.Font("TH Sarabun New", 1, 14)); // NOI18N

        Fname_Box.setFont(new java.awt.Font("TH Sarabun New", 1, 14)); // NOI18N

        Lname_Box.setFont(new java.awt.Font("TH Sarabun New", 1, 14)); // NOI18N

        Fac_Box.setFont(new java.awt.Font("TH Sarabun New", 1, 14)); // NOI18N

        GPAX_Box.setFont(new java.awt.Font("TH Sarabun New", 1, 14)); // NOI18N

        Submit_Btn.setBackground(new java.awt.Color(0, 102, 255));
        Submit_Btn.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        Submit_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Submit_Btn.setText("SUBMIT");
        Submit_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Submit_BtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GPAX_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GPAX_Box))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fac_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fac_Box))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lname_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lname_Box))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Fname_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fname_Box))
                    .addComponent(Title_txt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ID_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(Submit_Btn)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Title_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_Label)
                    .addComponent(ID_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fname_Label)
                    .addComponent(Fname_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname_Label)
                    .addComponent(Lname_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fac_Label)
                    .addComponent(Fac_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPAX_Label)
                    .addComponent(GPAX_Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(Submit_Btn)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Submit_BtnMouseClicked
        // TODO add your handling code here:
        String ID = ID_Box.getText();
        String Fname = Fname_Box.getText();
        String Lname = Lname_Box.getText();
        String Faculty = Fac_Box.getText();
        String GPAX = GPAX_Box.getText();

        Connection conn = null;
        String dbUrl = "jdbc:mysql://localhost/dbtable";
        try {
            conn = DriverManager.getConnection(dbUrl, "root", "");

            String query = "INSERT INTO students (ID, FirstName, LastName, Faculty, GPAX) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ptmt = conn.prepareStatement(query);
            ptmt.setString(1, ID);
            ptmt.setString(2, Fname);
            ptmt.setString(3, Lname);
            ptmt.setString(4, Faculty);
            ptmt.setString(5, GPAX);
            
            ptmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Insert successfully");
            Clear();

        } catch (SQLException ex) {
            System.out.println("SQLException: " + ex.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println("SQLException: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_Submit_BtnMouseClicked

    private void Clear() {
        ID_Box.setText("");
        Fname_Box.setText("");
        Lname_Box.setText("");
        Fac_Box.setText("");
        GPAX_Box.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fac_Box;
    private javax.swing.JLabel Fac_Label;
    private javax.swing.JTextField Fname_Box;
    private javax.swing.JLabel Fname_Label;
    private javax.swing.JTextField GPAX_Box;
    private javax.swing.JLabel GPAX_Label;
    private javax.swing.JTextField ID_Box;
    private javax.swing.JLabel ID_Label;
    private javax.swing.JTextField Lname_Box;
    private javax.swing.JLabel Lname_Label;
    private javax.swing.JButton Submit_Btn;
    private javax.swing.JLabel Title_txt;
    // End of variables declaration//GEN-END:variables
}
